#!/usr/bin/env bash
# =============================================================================
# ArdouraAI – Vultr Cloud-Init Startup Script
# Runs once at first boot as root.
# Installs Docker, clones the repo, injects secrets, launches the stack.
# =============================================================================
set -euo pipefail
LOG=/var/log/ardoura-init.log
exec > >(tee -a "$LOG") 2>&1

echo "[ardoura-init] === Starting at $(date) ==="

# ---------------------------------------------------------------------------
# 1. System updates + Docker
# ---------------------------------------------------------------------------
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  ca-certificates curl gnupg lsb-release \
  git jq python3 python3-pip python3-venv \
  nginx certbot python3-certbot-nginx

# Docker CE
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
  | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo \
  "deb [arch=$(dpkg --print-architecture) \
  signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] \
  https://download.docker.com/linux/ubuntu \
  $(lsb_release -cs) stable" \
  > /etc/apt/sources.list.d/docker.list
apt-get update -qq
apt-get install -y -qq docker-ce docker-ce-cli containerd.io docker-compose-plugin

systemctl enable docker
systemctl start docker

echo "[ardoura-init] Docker installed: $(docker --version)"

# ---------------------------------------------------------------------------
# 2. Clone / update the ArdouraAI repository
# ---------------------------------------------------------------------------
APP_DIR=/opt/ardoura

if [ -d "$APP_DIR/.git" ]; then
  echo "[ardoura-init] Updating existing repo..."
  git -C "$APP_DIR" pull --ff-only
else
  echo "[ardoura-init] Cloning repo..."
  git clone https://github.com/ashishPropt/ardouraAI.git "$APP_DIR"
fi

# ---------------------------------------------------------------------------
# 3. Parse user-data JSON for Vultr-managed DB credentials
#    (injected by Terraform as instance user_data)
# ---------------------------------------------------------------------------
UD_FILE="/var/lib/cloud/instance/user-data.txt"
if [ -f "$UD_FILE" ]; then
  DB_HOST=$(jq -r '.db_host'     "$UD_FILE" 2>/dev/null || echo "")
  DB_PORT=$(jq -r '.db_port'     "$UD_FILE" 2>/dev/null || echo "3306")
  DB_USER=$(jq -r '.db_user'     "$UD_FILE" 2>/dev/null || echo "")
  DB_PASS=$(jq -r '.db_password' "$UD_FILE" 2>/dev/null || echo "")
  DB_NAME=$(jq -r '.db_name'     "$UD_FILE" 2>/dev/null || echo "ardoura")
else
  DB_HOST=""; DB_PORT="3306"; DB_USER=""; DB_PASS=""; DB_NAME="ardoura"
  echo "[ardoura-init] WARNING: no user-data found; DB env vars will be blank"
fi

# ---------------------------------------------------------------------------
# 4. Write .env from template + Vultr-supplied values
#    Secrets the operator must supply go into /etc/ardoura/secrets.env
#    and are merged here at boot time.
# ---------------------------------------------------------------------------
SECRETS_FILE=/etc/ardoura/secrets.env
mkdir -p /etc/ardoura
chmod 700 /etc/ardoura

# Create skeleton secrets file if it doesn't exist yet
if [ ! -f "$SECRETS_FILE" ]; then
  cat > "$SECRETS_FILE" << 'SECRETS_EOF'
# Fill in your secrets – this file persists across deploys.
# Run: nano /etc/ardoura/secrets.env   then: systemctl restart ardoura
ANTHROPIC_API_KEY=REPLACE_ME
GITHUB_TOKEN=REPLACE_ME
APP_GITHUB_OWNER=ashishPropt
APP_GITHUB_REPO=ardouraAI
APP_GITHUB_BRANCH=main
ATLASSIAN_BASE=https://REPLACE_ME.atlassian.net
ATLASSIAN_EMAIL=REPLACE_ME@example.com
ATLASSIAN_API_TOKEN=REPLACE_ME
JIRA_SOURCE_PROJECT_KEY=ADEV
JIRA_ACTION_PROJECT_KEY=ACR
CONFLUENCE_DOC_PAGE_ID=0
CONFLUENCE_TROUBLESHOOT_PAGE_ID=0
CONFLUENCE_SPACE_KEY=~REPLACE_ME
CONFLUENCE_BASE_URL=https://REPLACE_ME.atlassian.net/wiki
DYNATRACE_URL=
DYNATRACE_API_TOKEN=
DATADOG_API_KEY=
DATADOG_APP_KEY=
DATADOG_SITE=datadoghq.com
GRAFANA_URL=
GRAFANA_API_KEY=
PROMETHEUS_URL=http://localhost:9090
SECRETS_EOF
  echo "[ardoura-init] Created $SECRETS_FILE – operator must fill in secrets!"
fi

# Merge template + Vultr DB values + operator secrets into .env
set -a
source "$SECRETS_FILE"
set +a

cat > "$APP_DIR/.env" << ENV_EOF
# Auto-generated by ardoura cloud-init at $(date)
# DO NOT EDIT – managed by /etc/ardoura/secrets.env + Terraform user_data

# --- Anthropic ---
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}

# --- GitHub ---
GITHUB_TOKEN=${GITHUB_TOKEN:-}
APP_GITHUB_OWNER=${APP_GITHUB_OWNER:-ashishPropt}
APP_GITHUB_REPO=${APP_GITHUB_REPO:-ardouraAI}
APP_GITHUB_BRANCH=${APP_GITHUB_BRANCH:-main}

# --- Atlassian ---
ATLASSIAN_BASE=${ATLASSIAN_BASE:-}
ATLASSIAN_EMAIL=${ATLASSIAN_EMAIL:-}
ATLASSIAN_API_TOKEN=${ATLASSIAN_API_TOKEN:-}
JIRA_SOURCE_PROJECT_KEY=${JIRA_SOURCE_PROJECT_KEY:-ADEV}
JIRA_ACTION_PROJECT_KEY=${JIRA_ACTION_PROJECT_KEY:-ACR}
CONFLUENCE_DOC_PAGE_ID=${CONFLUENCE_DOC_PAGE_ID:-0}
CONFLUENCE_TROUBLESHOOT_PAGE_ID=${CONFLUENCE_TROUBLESHOOT_PAGE_ID:-0}
CONFLUENCE_SPACE_KEY=${CONFLUENCE_SPACE_KEY:-}
CONFLUENCE_BASE_URL=${CONFLUENCE_BASE_URL:-}

# --- Kafka (internal Docker network) ---
KAFKA_BOOTSTRAP_SERVERS=kafka:9092
KAFKA_TOPIC=jira-events
KAFKA_GROUP_ID=jira-agent-group
KAFKA_TARGET_PROJECT_KEY=${JIRA_SOURCE_PROJECT_KEY:-ADEV}
KAFKA_TARGET_WEBHOOK_EVENT=jira:issue_created

# --- Flask ---
FLASK_PORT=5000

# --- MySQL (Vultr Managed DB) ---
DB_HOST=${DB_HOST:-}
DB_PORT=${DB_PORT:-3306}
DB_NAME=${DB_NAME:-ardoura}
DB_USER=${DB_USER:-}
DB_PASSWORD=${DB_PASS:-}
DB_ALLOW_DESTRUCTIVE=false

# --- Observability ---
DYNATRACE_URL=${DYNATRACE_URL:-}
DYNATRACE_API_TOKEN=${DYNATRACE_API_TOKEN:-}
DATADOG_API_KEY=${DATADOG_API_KEY:-}
DATADOG_APP_KEY=${DATADOG_APP_KEY:-}
DATADOG_SITE=${DATADOG_SITE:-datadoghq.com}
GRAFANA_URL=${GRAFANA_URL:-}
GRAFANA_API_KEY=${GRAFANA_API_KEY:-}
PROMETHEUS_URL=${PROMETHEUS_URL:-http://localhost:9090}
DYNATRACE_MIN_SEVERITY=ERROR
DATADOG_MIN_SEVERITY=error
GRAFANA_MIN_SEVERITY=warning
ENV_EOF

chmod 600 "$APP_DIR/.env"
echo "[ardoura-init] .env written"

# ---------------------------------------------------------------------------
# 5. Patch mcp_config.json to use Linux paths
# ---------------------------------------------------------------------------
jq --arg dir "$APP_DIR" '
  .mcpServers |= with_entries(
    .value.cwd = $dir
  )
' "$APP_DIR/mcp_config.json" > /tmp/mcp_config_patched.json
mv /tmp/mcp_config_patched.json "$APP_DIR/mcp_config.json"
echo "[ardoura-init] mcp_config.json patched with cwd=$APP_DIR"

# ---------------------------------------------------------------------------
# 6. Launch the Docker Compose stack
# ---------------------------------------------------------------------------
cd "$APP_DIR"
docker compose -f deploy/vultr/docker-compose.yml pull --quiet
docker compose -f deploy/vultr/docker-compose.yml up -d --remove-orphans
echo "[ardoura-init] Docker Compose stack started"

# ---------------------------------------------------------------------------
# 7. Install systemd unit so the stack survives reboots
# ---------------------------------------------------------------------------
cat > /etc/systemd/system/ardoura.service << SVC_EOF
[Unit]
Description=ArdouraAI Docker Compose stack
After=docker.service network-online.target
Requires=docker.service

[Service]
Type=oneshot
RemainAfterExit=yes
WorkingDirectory=/opt/ardoura
ExecStart=/usr/bin/docker compose -f deploy/vultr/docker-compose.yml up -d --remove-orphans
ExecStop=/usr/bin/docker compose  -f deploy/vultr/docker-compose.yml down
TimeoutStartSec=120

[Install]
WantedBy=multi-user.target
SVC_EOF

systemctl daemon-reload
systemctl enable ardoura
echo "[ardoura-init] systemd unit ardoura.service enabled"

# ---------------------------------------------------------------------------
# 8. Nginx reverse-proxy on port 80 → Flask 5000
# ---------------------------------------------------------------------------
cat > /etc/nginx/sites-available/ardoura << 'NGINX_EOF'
server {
    listen 80;
    server_name _;

    location / {
        proxy_pass         http://127.0.0.1:5000;
        proxy_set_header   Host $host;
        proxy_set_header   X-Real-IP $remote_addr;
        proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 120s;
    }

    location /health {
        proxy_pass http://127.0.0.1:5000/health;
        access_log off;
    }
}
NGINX_EOF

ln -sf /etc/nginx/sites-available/ardoura /etc/nginx/sites-enabled/ardoura
rm -f /etc/nginx/sites-enabled/default
nginx -t && systemctl reload nginx
echo "[ardoura-init] Nginx configured"

echo "[ardoura-init] === Finished at $(date) ==="
echo "[ardoura-init] Next: ssh into the box, fill /etc/ardoura/secrets.env, then: systemctl restart ardoura"
